blank_issues_enabled: true
contact_links:
  - name: metachain Bridge UI Support
    url: https://support.metachain-i.co/hc/en-gb/requests/new?ticket_form_id=18155929976987
    about: Please ask your specific questions here.
